# Generated by Django 4.2 on 2023-05-30 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=uuid.UUID('ab76c588-ff14-11ed-b323-a44e313181c0'), max_length=100),
        ),
    ]
