# Generated by Django 4.2 on 2023-07-25 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_alter_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images_path', models.JSONField()),
                ('predictions', models.JSONField()),
                ('processing_time', models.FloatField()),
                ('prediction_time', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=uuid.UUID('48035004-2aeb-11ee-bea2-39bb283fefc9'), max_length=100),
        ),
    ]
