# Generated by Django 4.2 on 2023-07-27 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=uuid.UUID('a3c4e380-2c5d-11ee-b024-a44e313181c0'), max_length=100),
        ),
    ]
